name: dart_waku
description: Dart bindings for the waku project.
version: 0.0.1
repository: https://github.com/helpisdev/dart_waku
homepage: https://docs.waku.org/dart_waku
documentation: https://waku.org
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  ffi: ^2.0.2
  path: ^1.8.3
  universal_io: ^2.2.2

dev_dependencies:
  ffigen: ^8.0.2
  melos: ^3.1.1
